apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-app-of-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-resources/rollouts/
    repoURL: https://github.com/fperearodriguez/multicluster-canary.git
    targetRevision: 'kvm-k8s'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  